### ISSUE TITLE
error being thrown when submitting a form offline

### ISSUE THREAD

**Issue by andreahall91** [veerwest/FormAssemblyMobileIssues#2]
Form that was throwing the error:
http://forms.thegoodcaregroup.com/20

Error was "Offline mode currently disabled for forms with attachments."

The form has a prefill SF connector, submit SF connector, and repeating sections. 

I was unable to reproduce this on my own forms. 

![screen shot 2016-09-28 at 9 45 25 am](https://cloud.githubusercontent.com/assets/22504556/18925342/9d71a2be-8581-11e6-93a6-cd8273af0ef5.png)

**Comment by drewbuschhorn** [comment]
Moved to JIRA
